SECRET_KEY = '1357902468*ronin*1357902468'

RECAPTCHA_PUBLIC_KEY = '6Lf_wu8SAAAAAOChm0g_NdoTWT1KQVR65fMbLUGq'
RECAPTCHA_PRIVATE_KEY = '6Lf_wu8SAAAAANGBgLZvhUlXpPLqSsbKQ_LvJCbI'
#RECAPTCHA_OPTIONS = {'theme': 'red'}

MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = 'jackosinapsis@gmail.com'
MAIL_PASSWORD = 'psw' 
